# Generated by Django 4.1.4 on 2023-01-01 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, null=True)),
                ('category_type', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=15)),
                ('updated_by', models.CharField(max_length=15)),
                ('datamode', models.CharField(choices=[('A', 'ACTIVE'), ('IN', 'Inactive'), ('D', 'Deleted')], db_index=True, default='A', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_model', models.CharField(blank=True, max_length=15, null=True)),
                ('product_price', models.CharField(blank=True, max_length=15, null=True)),
                ('product_offer', models.CharField(max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=10)),
                ('updated_by', models.CharField(max_length=10)),
                ('datamode', models.CharField(choices=[('A', 'ACTIVE'), ('IN', 'Inactive'), ('D', 'Deleted')], db_index=True, default='A', max_length=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
