# Generated by Django 4.1.4 on 2023-01-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(db_index=True, default='product_name', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(db_index=True, default='product_name', max_length=255),
        ),
    ]
